# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Niloufar Eghbali"
title_separator          : "-"
name                     : &name "Niloufar Eghbali"
description              : &description "Computer Science Ph.D. Student "
url                      : https://nilloufar.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "nilloufar/nilloufar.github.io"

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: CV, Niloufar Eghbali,
description: Personel CV
canonical: https://nilloufar.github.io/

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Niloufar Eghbali"
  pronouns         : # example: "she/her"  
  bio              : "Computer Science Ph.D. Student"
  location         : "East Lansing, MI, USA."
  employer         : "Michigan State University"
  uri              : # URL
  email            : "eghbaliz@msu.edu" 

  # Academic websites
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=IDOuCg0AAAAJ&hl=en"

  # Repositories and software development
  github           : "nilloufar"


remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README_de.md
  - LICENSE
  - minimal-light.gemspec